# Generated by Django 4.1.2 on 2022-10-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Группа тегов')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Имя тега')),
                ('tag_table', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Таблица тегов')),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Адрес в памяти')),
                ('data_type', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Тип данных')),
                ('comment', models.CharField(blank=True, default='no comment', max_length=100, verbose_name='Комментарий')),
                ('label', models.ForeignKey(db_column='label', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='analytics.group', verbose_name='Группа тегов')),
            ],
            options={
                'verbose_name': 'Теги',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
