# Generated by Django 4.1.2 on 2022-10-31 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='label',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='tags',
            name='label',
            field=models.ForeignKey(db_column='name', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='label', to='analytics.group', verbose_name='Группа тегов'),
        ),
    ]
