# Generated by Django 4.1.2 on 2022-10-13 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Dataset name')),
                ('is_historical', models.BooleanField(default=True, verbose_name='Historical dataset')),
                ('date_time_start_diapason', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Beginning time')),
                ('date_time_end_diapason', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ending time')),
                ('url', models.SlugField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('dataset_image', models.ImageField(upload_to='dataset_images/%Y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Dataset name',
                'verbose_name_plural': 'Datasets name',
            },
        ),
    ]
