# Generated by Django 4.1.2 on 2022-10-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataset',
            name='tag',
            field=models.ManyToManyField(to='analytics.tags'),
        ),
    ]
