# Generated by Django 4.1.2 on 2022-10-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0004_alter_userdataset_dataset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataset',
            name='tag',
            field=models.ManyToManyField(blank=True, to='analytics.tags'),
        ),
    ]
