# Generated by Django 4.1.2 on 2022-10-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userdataset_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdataset',
            name='tag',
        ),
    ]
