# Generated by Django 4.1.2 on 2022-10-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0006_remove_userdataset_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataset',
            name='tag',
            field=models.ManyToManyField(blank=True, to='analytics.tags'),
        ),
    ]
