# Generated by Django 4.1.2 on 2022-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0011_alter_userdataset_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataset',
            name='tag',
            field=models.ManyToManyField(related_query_name='tag', to='analytics.tags'),
        ),
    ]
